/**
 * pr-stats
 * Copyright (c) 2023-present NAVER Corp.
 * Apache-2.0
 */

import type {IPRData} from "@/types";

export const DUMMY_PR_DATA: IPRData = {
    pr: {
        url: "dummy_url",
        id: 3035061,
        node_id: "dummy_node_id",
        html_url: "dummy_url",
        diff_url: "dummy_url",
        patch_url: "dummy_url",
        issue_url: "dummy_url",
        number: 2520,
        state: "closed",
        locked: false,
        title: "feat(-): dummy PR title",
        user: {
            login: "user-1",
            id: 7079,
            node_id: "dummy_node_id",
            avatar_url: "dummy_url",
            gravatar_id: "",
            url: "dummy_url",
            html_url: "dummy_url",
            followers_url: "dummy_url",
            following_url: "dummy_url",
            gists_url: "dummy_url",
            starred_url: "dummy_url",
            subscriptions_url: "dummy_url",
            organizations_url: "dummy_url",
            repos_url: "dummy_url",
            events_url: "dummy_url",
            received_events_url: "dummy_url",
            type: "User",
            site_admin: false,
        },
        body: "dummy PR body",
        created_at: "2023-09-18T07:53:28Z",
        updated_at: "2023-09-20T02:47:50Z",
        closed_at: "2023-09-20T02:47:18Z",
        merged_at: "2023-09-20T02:47:18Z",
        merge_commit_sha: "dummy",
        assignee: {
            login: "user-1",
            id: 7079,
            node_id: "dummy_node_id",
            avatar_url: "dummy_url",
            gravatar_id: "",
            url: "dummy_url",
            html_url: "dummy_url",
            followers_url: "dummy_url",
            following_url: "dummy_url",
            gists_url: "dummy_url",
            starred_url: "dummy_url",
            subscriptions_url: "dummy_url",
            organizations_url: "dummy_url",
            repos_url: "dummy_url",
            events_url: "dummy_url",
            received_events_url: "dummy_url",
            type: "User",
            site_admin: false,
        },
        assignees: [
            {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
        ],
        requested_reviewers: [
            {
                login: "user-2",
                id: 209,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            {
                login: "user-6",
                id: 12335,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            {
                login: "user-7",
                id: 26161,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
        ],
        requested_teams: [],
        labels: [],
        milestone: null,
        draft: false,
        commits_url: "dummy_url",
        review_comments_url: "dummy_url",
        review_comment_url: "dummy_url",
        comments_url: "dummy_url",
        statuses_url: "dummy_url",
        head: {
            label: "dummy",
            ref: "dummy",
            sha: "dummy",
            user: {
                login: "dummy",
                id: 350,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "Organization",
                site_admin: false,
            },
            repo: {
                id: 79133,
                node_id: "dummy_node_id",
                name: "dummy name",
                full_name: "dummy repo name",
                private: true,
                owner: {
                    login: "dummy",
                    id: 350,
                    node_id: "dummy_node_id",
                    avatar_url: "dummy_url",
                    gravatar_id: "",
                    url: "dummy_url",
                    html_url: "dummy_url",
                    followers_url: "dummy_url",
                    following_url: "dummy_url",
                    gists_url: "dummy_url",
                    starred_url: "dummy_url",
                    subscriptions_url: "dummy_url",
                    organizations_url: "dummy_url",
                    repos_url: "dummy_url",
                    events_url: "dummy_url",
                    received_events_url: "dummy_url",
                    type: "Organization",
                    site_admin: false,
                },
                html_url: "dummy_url",
                description: "dummy description",
                fork: false,
                url: "dummy_url",
                forks_url: "dummy_url",
                keys_url: "dummy_url",
                collaborators_url: "dummy_url",
                teams_url: "dummy_url",
                hooks_url: "dummy_url",
                issue_events_url: "dummy_url",
                events_url: "dummy_url",
                assignees_url: "dummy_url",
                branches_url: "dummy_url",
                tags_url: "dummy_url",
                blobs_url: "dummy_url",
                git_tags_url: "dummy_url",
                git_refs_url: "dummy_url",
                trees_url: "dummy_url",
                statuses_url: "dummy_url",
                languages_url: "dummy_url",
                stargazers_url: "dummy_url",
                contributors_url: "dummy_url",
                subscribers_url: "dummy_url",
                subscription_url: "dummy_url",
                commits_url: "dummy_url",
                git_commits_url: "dummy_url",
                comments_url: "dummy_url",
                issue_comment_url: "dummy_url",
                contents_url: "dummy_url",
                compare_url: "dummy_url",
                merges_url: "dummy_url",
                archive_url: "dummy_url",
                downloads_url: "dummy_url",
                issues_url: "dummy_url",
                pulls_url: "dummy_url",
                milestones_url: "dummy_url",
                notifications_url: "dummy_url",
                labels_url: "dummy_url",
                releases_url: "dummy_url",
                deployments_url: "dummy_url",
                created_at: "2020-01-31T02:00:44Z",
                updated_at: "2023-04-07T07:09:37Z",
                pushed_at: "2023-09-27T04:27:58Z",
                git_url: "dummy_url",
                ssh_url: "dummy_url",
                clone_url: "dummy_url",
                svn_url: "dummy_url",
                homepage: null,
                size: 347584,
                stargazers_count: 5,
                watchers_count: 5,
                language: "JavaScript",
                has_issues: true,
                has_projects: true,
                has_downloads: true,
                has_wiki: true,
                has_pages: false,
                forks_count: 1,
                mirror_url: null,
                archived: false,
                disabled: false,
                open_issues_count: 9,
                license: null,
                allow_forking: true,
                is_template: false,
                topics: [],
                visibility: "private",
                forks: 1,
                open_issues: 9,
                watchers: 5,
                default_branch: "develop",
            },
        },
        base: {
            label: "dummy",
            ref: "dummy",
            sha: "dummy",
            user: {
                login: "dummy",
                id: 350,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "Organization",
                site_admin: false,
            },
            repo: {
                id: 79133,
                node_id: "dummy_node_id",
                name: "dummy name",
                full_name: "dummy repo name",
                private: true,
                owner: {
                    login: "dummy",
                    id: 350,
                    node_id: "dummy_node_id",
                    avatar_url: "dummy_url",
                    gravatar_id: "",
                    url: "dummy_url",
                    html_url: "dummy_url",
                    followers_url: "dummy_url",
                    following_url: "dummy_url",
                    gists_url: "dummy_url",
                    starred_url: "dummy_url",
                    subscriptions_url: "dummy_url",
                    organizations_url: "dummy_url",
                    repos_url: "dummy_url",
                    events_url: "dummy_url",
                    received_events_url: "dummy_url",
                    type: "Organization",
                    site_admin: false,
                },
                html_url: "dummy_url",
                description: "dummy description",
                fork: false,
                url: "dummy_url",
                forks_url: "dummy_url",
                keys_url: "dummy_url",
                collaborators_url: "dummy_url",
                teams_url: "dummy_url",
                hooks_url: "dummy_url",
                issue_events_url: "dummy_url",
                events_url: "dummy_url",
                assignees_url: "dummy_url",
                branches_url: "dummy_url",
                tags_url: "dummy_url",
                blobs_url: "dummy_url",
                git_tags_url: "dummy_url",
                git_refs_url: "dummy_url",
                trees_url: "dummy_url",
                statuses_url: "dummy_url",
                languages_url: "dummy_url",
                stargazers_url: "dummy_url",
                contributors_url: "dummy_url",
                subscribers_url: "dummy_url",
                subscription_url: "dummy_url",
                commits_url: "dummy_url",
                git_commits_url: "dummy_url",
                comments_url: "dummy_url",
                issue_comment_url: "dummy_url",
                contents_url: "dummy_url",
                compare_url: "dummy_url",
                merges_url: "dummy_url",
                archive_url: "dummy_url",
                downloads_url: "dummy_url",
                issues_url: "dummy_url",
                pulls_url: "dummy_url",
                milestones_url: "dummy_url",
                notifications_url: "dummy_url",
                labels_url: "dummy_url",
                releases_url: "dummy_url",
                deployments_url: "dummy_url",
                created_at: "2020-01-31T02:00:44Z",
                updated_at: "2023-04-07T07:09:37Z",
                pushed_at: "2023-09-27T04:27:58Z",
                git_url: "dummy_url",
                ssh_url: "dummy_url",
                clone_url: "dummy_url",
                svn_url: "dummy_url",
                homepage: null,
                size: 347584,
                stargazers_count: 5,
                watchers_count: 5,
                language: "JavaScript",
                has_issues: true,
                has_projects: true,
                has_downloads: true,
                has_wiki: true,
                has_pages: false,
                forks_count: 1,
                mirror_url: null,
                archived: false,
                disabled: false,
                open_issues_count: 9,
                license: null,
                allow_forking: true,
                is_template: false,
                topics: [],
                visibility: "private",
                forks: 1,
                open_issues: 9,
                watchers: 5,
                default_branch: "develop",
            },
        },
        _links: {
            self: {href: "dummy_url"},
            html: {href: "dummy_url"},
            issue: {href: "dummy_url"},
            comments: {href: "dummy_url"},
            review_comments: {href: "dummy_url"},
            review_comment: {href: "dummy_url"},
            commits: {href: "dummy_url"},
            statuses: {
                href: "dummy_url",
            },
        },
        author_association: "CONTRIBUTOR",
        auto_merge: {
            enabled_by: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            merge_method: "merge",
            commit_title: "Merge pull request ...",
            commit_message: "feat(-): dummy commit message",
        },
        active_lock_reason: null,
        merged: true,
        mergeable: null,
        rebaseable: null,
        mergeable_state: "unknown",
        merged_by: {
            login: "user-1",
            id: 7079,
            node_id: "dummy_node_id",
            avatar_url: "dummy_url",
            gravatar_id: "",
            url: "dummy_url",
            html_url: "dummy_url",
            followers_url: "dummy_url",
            following_url: "dummy_url",
            gists_url: "dummy_url",
            starred_url: "dummy_url",
            subscriptions_url: "dummy_url",
            organizations_url: "dummy_url",
            repos_url: "dummy_url",
            events_url: "dummy_url",
            received_events_url: "dummy_url",
            type: "User",
            site_admin: false,
        },
        comments: 13,
        review_comments: 3,
        maintainer_can_modify: false,
        commits: 6,
        additions: 41,
        deletions: 35,
        changed_files: 1,
    },
    events: [
        {
            sha: "dummy",
            node_id: "dummy_node_id",
            url: "dummy_url",
            html_url: "dummy_url",
            author: {name: "user-1", email: "user1@email.com", date: "2023-09-18T07:50:11Z"},
            committer: {name: "user-1", email: "user1@email.com", date: "2023-09-18T07:50:11Z"},
            tree: {
                sha: "dummy",
                url: "dummy_url",
            },
            message: "feat(-): dummy commit message",
            parents: [
                {
                    sha: "dummy",
                    url: "dummy_url",
                    html_url: "dummy_url",
                },
            ],
            verification: {verified: false, reason: "unsigned", signature: null, payload: null},
            event: "committed",
        },
        {
            sha: "dummy",
            node_id: "dummy_node_id",
            url: "dummy_url",
            html_url: "dummy_url",
            author: {name: "user-1", email: "user1@email.com", date: "2023-09-18T07:52:29Z"},
            committer: {name: "user-1", email: "user1@email.com", date: "2023-09-18T07:52:29Z"},
            tree: {
                sha: "dummy",
                url: "dummy_url",
            },
            message: "feat(-): dummy commit message",
            parents: [
                {
                    sha: "dummy",
                    url: "dummy_url",
                    html_url: "dummy_url",
                },
            ],
            verification: {verified: false, reason: "unsigned", signature: null, payload: null},
            event: "committed",
        },
        {
            id: 52339807,
            node_id: "dummy_node_id",
            url: "dummy_url",
            actor: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            event: "assigned",
            commit_id: null,
            commit_url: null,
            created_at: "2023-09-18T07:53:28Z",
            assignee: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            performed_via_github_app: null,
        },
        {
            id: 52339864,
            node_id: "dummy_node_id",
            url: "dummy_url",
            actor: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            event: "renamed",
            commit_id: null,
            commit_url: null,
            created_at: "2023-09-18T07:54:06Z",
            rename: {
                from: "Feat/dummy from title",
                to: "feat(-): dummy to title",
            },
            performed_via_github_app: null,
        },
        {
            id: 52340395,
            node_id: "dummy_node_id",
            url: "dummy_url",
            actor: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            event: "review_requested",
            commit_id: null,
            commit_url: null,
            created_at: "2023-09-18T07:57:47Z",
            review_requester: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            requested_reviewer: {
                login: "user-2",
                id: 209,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            performed_via_github_app: null,
        },
        {
            id: 52340396,
            node_id: "dummy_node_id",
            url: "dummy_url",
            actor: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            event: "review_requested",
            commit_id: null,
            commit_url: null,
            created_at: "2023-09-18T07:57:47Z",
            review_requester: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            requested_reviewer: {
                login: "user-3",
                id: 133,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            performed_via_github_app: null,
        },
        {
            id: 52340397,
            node_id: "dummy_node_id",
            url: "dummy_url",
            actor: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            event: "review_requested",
            commit_id: null,
            commit_url: null,
            created_at: "2023-09-18T07:57:47Z",
            review_requester: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            requested_reviewer: {
                login: "user-4",
                id: 11734,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            performed_via_github_app: null,
        },
        {
            url: "dummy_url",
            html_url: "dummy_url",
            issue_url: "dummy_url",
            id: 11249675,
            node_id: "dummy_node_id",
            user: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            created_at: "2023-09-18T07:58:23Z",
            updated_at: "2023-09-18T08:02:06Z",
            author_association: "CONTRIBUTOR",
            body: "issueComment1",
            reactions: {
                url: "dummy_url",
                total_count: 0,
                "+1": 0,
                "-1": 0,
                laugh: 0,
                hooray: 0,
                confused: 0,
                heart: 0,
                rocket: 0,
                eyes: 0,
            },
            performed_via_github_app: null,
            event: "commented",
            actor: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
        },
        {
            url: "dummy_url",
            html_url: "dummy_url",
            issue_url: "dummy_url",
            id: 11251162,
            node_id: "dummy_node_id",
            user: {
                login: "user-2",
                id: 209,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            created_at: "2023-09-18T09:03:36Z",
            updated_at: "2023-09-18T09:03:36Z",
            author_association: "CONTRIBUTOR",
            body: "issueComment2",
            reactions: {
                url: "dummy_url",
                total_count: 0,
                "+1": 0,
                "-1": 0,
                laugh: 0,
                hooray: 0,
                confused: 0,
                heart: 0,
                rocket: 0,
                eyes: 0,
            },
            performed_via_github_app: null,
            event: "commented",
            actor: {
                login: "user-2",
                id: 209,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
        },
        {
            url: "dummy_url",
            html_url: "dummy_url",
            issue_url: "dummy_url",
            id: 11325375,
            node_id: "dummy_node_id",
            user: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            created_at: "2023-09-18T23:16:33Z",
            updated_at: "2023-09-18T23:16:33Z",
            author_association: "CONTRIBUTOR",
            body: "issueComment3",
            reactions: {
                url: "dummy_url",
                total_count: 0,
                "+1": 0,
                "-1": 0,
                laugh: 0,
                hooray: 0,
                confused: 0,
                heart: 0,
                rocket: 0,
                eyes: 0,
            },
            performed_via_github_app: null,
            event: "commented",
            actor: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
        },
        {
            id: 52617012,
            node_id: "dummy_node_id",
            url: "dummy_url",
            actor: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },

            event: "merged",
            commit_id: "dummy_commit_id",
            commit_url: "dummy_url",
            created_at: "2023-09-18T23:47:33Z",
            performed_via_github_app: null,
        },
    ],
    reviewComments: [
        {
            url: "dummy_url",
            pull_request_review_id: 4839687,
            id: 3183945,
            node_id: "dummy_node_id",
            diff_hunk: "dummy",
            path: "dummy path",
            position: 27,
            original_position: 27,
            commit_id: "dummy_commit_id",
            original_commit_id: "dummy_commit_id",
            user: {
                login: "user-4",
                id: 11734,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            body: "codeComment1",
            created_at: "2023-09-19T03:31:26Z",
            updated_at: "2023-09-19T03:31:29Z",
            html_url: "dummy_url",
            pull_request_url: "dummy_url",
            author_association: "COLLABORATOR",
            _links: {
                self: {href: "dummy_url"},
                html: {href: "dummy_url"},
                pull_request: {href: "dummy_url"},
            },
            reactions: {
                url: "dummy_url",
                total_count: 0,
                "+1": 0,
                "-1": 0,
                laugh: 0,
                hooray: 0,
                confused: 0,
                heart: 0,
                rocket: 0,
                eyes: 0,
            },
            start_line: null,
            original_start_line: null,
            start_side: null,
            line: 237,
            original_line: 237,
            side: "RIGHT",
        },
        {
            url: "dummy_url",
            pull_request_review_id: 4840338,
            id: 3184328,
            node_id: "dummy_node_id",
            diff_hunk: "dummy",
            path: "dummy path",
            position: 27,
            original_position: 27,
            commit_id: "dummy_commit_id",
            original_commit_id: "dummy_commit_id",
            user: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            body: "codeComment2",
            created_at: "2023-09-19T05:09:34Z",
            updated_at: "2023-09-19T05:10:25Z",
            html_url: "dummy_url",
            pull_request_url: "dummy_url",
            author_association: "CONTRIBUTOR",
            _links: {
                self: {href: "dummy_url"},
                html: {href: "dummy_url"},
                pull_request: {href: "dummy_url"},
            },
            reactions: {
                url: "dummy_url",
                total_count: 0,
                "+1": 0,
                "-1": 0,
                laugh: 0,
                hooray: 0,
                confused: 0,
                heart: 0,
                rocket: 0,
                eyes: 0,
            },
            start_line: null,
            original_start_line: null,
            start_side: null,
            line: 237,
            original_line: 237,
            side: "RIGHT",
            in_reply_to_id: 3183945,
        },
        {
            url: "dummy_url",
            pull_request_review_id: 4844310,
            id: 3186864,
            node_id: "dummy_node_id",
            diff_hunk: "dummy",
            path: "dummy path",
            position: 27,
            original_position: 27,
            commit_id: "dummy_commit_id",
            original_commit_id: "dummy_commit_id",
            user: {
                login: "user-4",
                id: 11734,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            body: "dummy body",
            created_at: "2023-09-20T01:00:58Z",
            updated_at: "2023-09-20T01:00:58Z",
            html_url: "dummy_url",
            pull_request_url: "dummy_url",
            author_association: "COLLABORATOR",
            _links: {
                self: {href: "dummy_url"},
                html: {href: "dummy_url"},
                pull_request: {href: "dummy_url"},
            },
            reactions: {
                url: "dummy_url",
                total_count: 1,
                "+1": 0,
                "-1": 0,
                laugh: 0,
                hooray: 0,
                confused: 0,
                heart: 0,
                rocket: 0,
                eyes: 1,
            },
            start_line: null,
            original_start_line: null,
            start_side: null,
            line: 237,
            original_line: 237,
            side: "RIGHT",
            in_reply_to_id: 3183945,
        },
    ],
    reviews: [
        {
            id: 4839687,
            node_id: "dummy_node_id",
            user: {
                login: "user-4",
                id: 11734,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            body: "",
            state: "COMMENTED",
            html_url: "dummy_url",
            pull_request_url: "dummy_url",
            author_association: "COLLABORATOR",
            _links: {
                html: {href: "dummy_url"},
                pull_request: {href: "dummy_url"},
            },
            submitted_at: "2023-09-19T03:31:29Z",
            commit_id: "dummy_commit_id",
        },
        {
            id: 4840338,
            node_id: "dummy_node_id",
            user: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            body: "",
            state: "COMMENTED",
            html_url: "dummy_url",
            pull_request_url: "dummy_url",
            author_association: "CONTRIBUTOR",
            _links: {
                html: {href: "dummy_url"},
                pull_request: {href: "dummy_url"},
            },
            submitted_at: "2023-09-19T05:09:34Z",
            commit_id: "dummy_commit_id",
        },
        {
            id: 4844310,
            node_id: "dummy_node_id",
            user: {
                login: "user-4",
                id: 11734,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            body: "",
            state: "COMMENTED",
            html_url: "dummy_url",
            pull_request_url: "dummy_url",
            author_association: "COLLABORATOR",
            _links: {
                html: {href: "dummy_url"},
                pull_request: {href: "dummy_url"},
            },
            submitted_at: "2023-09-20T01:00:58Z",
            commit_id: "dummy_commit_id",
        },
        {
            id: 4844312,
            node_id: "dummy_node_id",
            user: {
                login: "user-4",
                id: 11734,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            body: "",
            state: "APPROVED",
            html_url: "dummy_url",
            pull_request_url: "dummy_url",
            author_association: "COLLABORATOR",
            _links: {
                html: {href: "dummy_url"},
                pull_request: {href: "dummy_url"},
            },
            submitted_at: "2023-09-20T01:01:13Z",
            commit_id: "dummy_commit_id",
        },
        {
            id: 4844956,
            node_id: "dummy_node_id",
            user: {
                login: "user-3",
                id: 133,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            body: "",
            state: "APPROVED",
            html_url: "dummy_url",
            pull_request_url: "dummy_url",
            author_association: "CONTRIBUTOR",
            _links: {
                html: {href: "dummy_url"},
                pull_request: {href: "dummy_url"},
            },
            submitted_at: "2023-09-20T02:00:41Z",
            commit_id: "dummy_commit_id",
        },
    ],
    comments: [
        {
            url: "dummy_url",
            html_url: "dummy_url",
            issue_url: "dummy_url",
            id: 11249675,
            node_id: "dummy_node_id",
            user: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            created_at: "2023-09-18T07:58:23Z",
            updated_at: "2023-09-18T08:02:06Z",
            author_association: "CONTRIBUTOR",
            body: "issueComment1",
            reactions: {
                url: "dummy_url",
                total_count: 0,
                "+1": 0,
                "-1": 0,
                laugh: 0,
                hooray: 0,
                confused: 0,
                heart: 0,
                rocket: 0,
                eyes: 0,
            },
            performed_via_github_app: null,
        },
        {
            url: "dummy_url",
            html_url: "dummy_url",
            issue_url: "dummy_url",
            id: 11251162,
            node_id: "dummy_node_id",
            user: {
                login: "user-2",
                id: 209,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            created_at: "2023-09-18T09:03:36Z",
            updated_at: "2023-09-18T09:03:36Z",
            author_association: "CONTRIBUTOR",
            body: "issueComment2",
            reactions: {
                url: "dummy_url",
                total_count: 0,
                "+1": 0,
                "-1": 0,
                laugh: 0,
                hooray: 0,
                confused: 0,
                heart: 0,
                rocket: 0,
                eyes: 0,
            },
            performed_via_github_app: null,
        },
        {
            url: "dummy_url",
            html_url: "dummy_url",
            issue_url: "dummy_url",
            id: 11325375,
            node_id: "dummy_node_id",
            user: {
                login: "user-1",
                id: 7079,
                node_id: "dummy_node_id",
                avatar_url: "dummy_url",
                gravatar_id: "",
                url: "dummy_url",
                html_url: "dummy_url",
                followers_url: "dummy_url",
                following_url: "dummy_url",
                gists_url: "dummy_url",
                starred_url: "dummy_url",
                subscriptions_url: "dummy_url",
                organizations_url: "dummy_url",
                repos_url: "dummy_url",
                events_url: "dummy_url",
                received_events_url: "dummy_url",
                type: "User",
                site_admin: false,
            },
            created_at: "2023-09-18T23:16:33Z",
            updated_at: "2023-09-18T23:16:33Z",
            author_association: "CONTRIBUTOR",
            body: "issueComment3",
            reactions: {
                url: "dummy_url",
                total_count: 0,
                "+1": 0,
                "-1": 0,
                laugh: 0,
                hooray: 0,
                confused: 0,
                heart: 0,
                rocket: 0,
                eyes: 0,
            },
            performed_via_github_app: null,
        },
    ],
};
